---

# Main Ansible Playbook for building on-premise Kubernetes clusters 

- name: Configure Kubernetes cluster - OnPrem
  hosts: all
  gather_facts: true

  roles:
    - role: linux                      
    - role: k8s-packages                        
    - role: k8s-cluster-init           

...
